# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default # Change this to your self-hosted agent pool

variables:
  storageAccountName: "storagetestdevops1"
  containerName: "test-case"
  filePath: "$(Build.SourcesDirectory)/test.zip" # The file you want to upload
  servicePrincipalId: "3983444f-6dcc-4ac2-acd7-246817654d3e"
  tenantId: "ef2829b1-46d8-4b2a-b962-9241518e03f5"
  subscriptionId: "6f28a0a1-2e2a-4481-8787-d6c49d238489"

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'sp-testcase'
    scriptType: 'bash' # Use 'bash' for CLI commands
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Authenticate the service principal using Azure CLI
      az login --service-principal -u "$(servicePrincipalId)" -p "$(servicePrincipalKey)" --tenant "$(tenantId)"

      # Upload the file to the specified Azure Blob Storage container
      az storage blob upload --account-name "$(storageAccountName)" --container-name "$(containerName)" --file "$(filePath)" --name "test.zip" --auth-mode key --account-key "$(storageAccountKey)"
  
  env:
    servicePrincipalKey: $(servicePrincipalKey)
    storageAccountKey: $(storageAccountKey)
